server:
  port: 8001
  servlet:
    context-path: /webstore
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: lencho-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://hadoop104:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456

    url: jdbc:postgresql://hadoop104:5432/db01?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      #空闲连接是否被回收
      test-while-idle: true
      #申请连接时是否检测有效性
      test-on-borrow: false
      #归还连接时是否检测有效性
      test-on-return: false

export:
  datasource:
    druid:
      driverClassName: org.gjt.mm.mysql.Driver
      #配置基本属性
      url: jdbc:mysql://hadoop104:3306/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456

#  quartz:
#    #持久化到数据库方式
#    job-store-type: jdbc
#    scheduler-name: myScheduler # 相同 Scheduler 名字的节点，形成一个 Quartz 集群
#    wait-for-jobs-to-complete-on-shutdown: true # 应用关闭时，是否等待定时任务执行完成。默认为 false ，建议设置为 true
#    jdbc:
#      initialize-schema: never # 第一次初始化设置always 后面设置never
#    properties:
#      org:
#        quartz:
#          scheduler:
#            instanceName: MyScheduler
#            instanceId: AUTO
#          jobStore:
#            dataSource: quartzDataSource # 使用的数据源
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
#            tablePrefix: QRTZ_ # Quartz 表前缀
#            isClustered: false # 是集群模式
#            clusterCheckinInterval: 10000
#            #  jobdataMap的数据转化成blob字段时容易出错,
#            #  在quartz的文档中有推荐说jobdatamap都用string,可以避免此类错误
#            #  要做到限制全是string必须在quartz.properties中把org.quartz.jobStore.useProperties设成true
#            useProperties: true
#          threadPool:
#            class: org.quartz.simpl.SimpleThreadPool
#            threadCount: 10
#            threadPriority: 5
#            threadsInheritContextClassLoaderOfInitializingThread: true

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.geoway.webstore.entities
#  configuration:
#    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    cache-enabled: false
#    localCacheScope: STATEMENT

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.geoway.webstore.entity
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    localCacheScope: STATEMENT

# 配置pagehelper参数
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

###swagger如下都是非必须的配置（实际使用时请根据实际情况配置）
swagger:
  enabled: true
  title: 套合比对系统 - Powered by GEOWAY
  description: 套合比对系统接口文档
  termsOfServiceUrl: http://www.geoway.com.cn/
  contact:
    name: 北京吉威空间软件股份有限公司
    url: contact
    email:
  #接口包扫描路径
  base-package: com.geoway.webstore.controller
  #需排除的接口路径
  exclude-path:

logging:
  level: {root: debug}
  config: classpath:log4j2.xml

master:
  datasource:
    druid:
#      driverClassName: org.gjt.mm.mysql.Driver
#      #配置基本属性
#      url: jdbc:mysql://hadoop104:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: 123456

      url: jdbc:postgresql://hadoop104:5432/db01?useUnicode=true&characterEncoding=utf8
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: root

second:
  datasource:
    druid:
      driverClassName: org.gjt.mm.mysql.Driver
      #配置基本属性
      url: jdbc:mysql://hadoop104:3306/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456

#second:
#  datasource:
#    druid:
#      driverClassName: oracle.jdbc.driver.OracleDriver
#      #配置基本属性
#      url: jdbc:oracle:thin:@localhost:1521:ORCL
#      username: root
#      password: 123456

# 线程池配置
threadPool:
  core-pool-size: 10
  max-pool-size: 300
  queue-capacity: 1000
  keep-alive-seconds: 600
  threadNamePrefix: my-thread-

#tbsys_syspara表配置项
sys-para:
  scanIntervalKey: aadea8a9-b7ad-44e2-a7a4-6d37ae432742
  scanPathKey: eefc68d6-50d0-46ee-ae60-f7556941e92c
  scanPathsKey: a10519d2-85f3-4b06-b38a-2df9c6462623
  serviceStatusKey: add77e71-6603-4dd7-9ff9-6e2a947c398e

template-loader-path: classpath:templates
#\\192.168.102.18\Reports\words
report-export-path: D:/test/report

fr-report-export-url: http://localhost:9001
